KE-works/pykechain

.travis.yml, pykechain/models/property_attachment.py, tox.ini
- Added overloaded `upload` function to accept matplotlib figures, filenames and jsonify-able objects
- Added `json_load` function which loads reads json directly from attachment
=> Attachment download

pykechain/client.py, pykechain/models/part.py, pykechain/models/property.py
=> Add functionality to create part models

CHANGELOG.rst, pykechain/models/part.py, pykechain/models/property.py, pykechain/models/property_reference.py
=> added docs for the reference property

CHANGELOG.rst, docs/api/client.rst, docs/api/enums.rst, docs/api/exceptions.rst, docs/api/helpers.rst, docs/api/models_activity.rst, docs/api/models_base.rst, docs/api/models_part.rst, docs/api/models_property.rst, docs/api/models_scope.rst, pykechain/__about__.py, pykechain/client.py, pykechain/enums.py, pykechain/helpers.py, pykechain/models/part.py
* added get_project status attributre
* added Scopestatus Enums
* updated the Kecenv enums to include KECHAIN_SCOPE_STATUS to pass as envvar
* updated docs of client.login and part.children
=> #203 added get_project status attribute, updated docs

pykechain/enums.py, pykechain/models/base.py, pykechain/models/customization.py, pykechain/models/inspector_base.py, pykechain/models/property.py
=> type in property + documentation of enums

pykechain/models/validators/validators.py, tests/models/test_validators.py
=> Fixed numeric range validator

Pipfile, setup.py
=> updating requests > 2.20.0

.travis.yml, pykechain/client.py, pykechain/exceptions.py, pykechain/extra_utils.py, pykechain/helpers.py, pykechain/models/__init__.py, pykechain/models/part.py, pykechain/models/scope.py, pykechain/models/validators/validators.py, tox.ini
Continuation of the PIM3 branch improvements
* after the release of pykechain 2.7.0 we moved the `master` branch to the `master-legaxy-2.x` branch where continued development of the v2.7 code is performed
* the PIM3 branch is merged into `master` to prepare for the 3.0.0 release of pykechain.
* this PR are improvements on that master.
=> PIM3 Improvements PR

pykechain/__about__.py, pykechain/client.py
=> 714 implement retry for session

CHANGELOG.rst, pykechain/enums.py
=> Added property GeoJSON and Weather Properties

CHANGELOG.rst, pykechain/models/widgets/widgets_manager.py
=> #814: Added `upload` input value

CHANGELOG.rst, pykechain/models/base_reference.py, pykechain/models/property_multi_reference.py, pykechain/models/property_reference.py, tests/models/test_property_reference.py, tests/test_utils.py
=> Fixes to internal reference _value

.github/workflows/python_testing.yml, CHANGELOG.rst, pykechain/client.py, pykechain/enums.py, tests/test_services.py
=> 897 - support of Python 3.8 has been added

CHANGELOG.rst, pykechain/models/widgets/widgets_manager.py
=> 901 - fixed a small bug on the enums of a widget

CHANGELOG.rst, pykechain/__about__.py, pykechain/extra_utils.py
=> Release 3.10.0

CHANGELOG.rst, pykechain/exceptions.py, pykechain/models/activity.py, pykechain/models/activity2.py, pykechain/models/part.py, pykechain/models/part2.py, pykechain/models/property.py, pykechain/models/property2.py, pykechain/models/property2_activity_reference.py, pykechain/models/property2_attachment.py, pykechain/models/property2_datetime.py, pykechain/models/property2_multi_reference.py, pykechain/models/property2_selectlist.py, pykechain/models/property_attachment.py, pykechain/models/property_datetime.py, pykechain/models/property_multi_reference.py, pykechain/models/property_reference.py, pykechain/models/property_selectlist.py, pykechain/models/scope.py, pykechain/models/scope2.py
=> Refactor  the Scope2, Part2 and other '2' models

CHANGELOG.rst, pykechain/enums.py
=> use Property Name representation

CHANGELOG.rst, pykechain/models/property.py, pykechain/models/validators/validator_schemas.py
=> #1029-lazy-validation-of-prop-options-json

CHANGELOG.rst, pykechain/__about__.py
=> version 3.17.1

pykechain/models/form.py, tests/test_forms.py
=> added statusform concept

CHANGELOG.rst, pykechain/client.py, pykechain/defaults.py, pykechain/models/user.py, tests/test_users.py
=> Create User Endpoint

pykechain/defaults.py, pykechain/exceptions.py, pykechain/models/activity.py
=> Added configurable timeout on PDF download

requirements.txt
=> updating requirements jsonschem to 4.5.1

CHANGELOG.rst, pykechain/__about__.py, pykechain/models/sidebar/sidebar_base.py, pykechain/models/sidebar/sidebar_button.py, pykechain/models/sidebar/sidebar_card.py, pykechain/models/sidebar/sidebar_manager.py, tests/test_sidebar.py
=> remove order from the sidebaritems.

.github/workflows/python_testing.yml
=> test-coveralls-token-err-and-testing-to-3.10

CHANGELOG.rst, pykechain/__about__.py
=> release v4.7.0 changelog and version

.github/workflows/python_testing.yml, build_wheel.sh, tests/test_activities.py, tests/test_expiring_downloads.py, tests/test_widgets.py
=> fixing broken tests in main

CHANGELOG.rst, pykechain/__about__.py
=> release v4.8.1

.github/workflows/python_testing.yml
=> added-python-311-tests

CHANGELOG.rst
=> Update CHANGELOG with multi-attachment replace behavior

CHANGELOG.rst, pykechain/client.py, pykechain/models/scope.py
=> Ke 5237 update user retrieval in scope
